### ISSUE TITLE
"gatsby-remark-images" now implemented "lazy" loading as its default loading behavior

### ISSUE THREAD

**Issue by minhnh94** [1kohei1/gatsby-remark-lazy-load#3]
According to the plugin official document, it now has lazy loading as its default loading behavior.
If able, can I know how this is different from your plugin?

**Comment by 1kohei1** [comment]
I see gatsby-remark-images introduced lazy loading in [version 3.1.10](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/CHANGELOG.md#3110-2019-08-11). When I made my blog on April 2019, it's not supported.
